{
 "title": "mmc-simulation",
 "time": { "from": "2026-02-19T09:16:01.967Z", "to": "2026-02-19T10:53:19.805Z" },
 "panels": [
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"simulation-group\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(messages_waiting_time_ms_milliseconds_sum[1m]))  / sum(increase(messages_waiting_time_ms_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(server_busy_time_total_ms_milliseconds_total[1m])) / (1000 * 4)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(messages_completed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization per Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(server_busy_time_total_ms_milliseconds_total[1m]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Service Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(messages_service_time_ms_milliseconds_sum[1m]))  / sum(increase(messages_service_time_ms_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(messages_response_time_ms_milliseconds_sum[1m]))  / sum(increase(messages_response_time_ms_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}